export const CheckBox = {
  Name: "CheckBox1",
  Accelerator: "",
  Alignment: "",
  AutoSize: false,
  BackColor: "white",
  BackStyle: "solid",
  Caption: "CheckBox1",
  ControlSource: "",
  ControlTipText: "",
  Enabled: true,
  Font: "Arial, Helvetica, sans-serif",
  ForeColor: "black",
  GroupName: "",
  Height: "100px",
  HelpContextId: 0,
  Left: "403px",
  Locked: false,
  MouseIcon: "(None)",
  MousePointer: "",
  Picture: "(None)",
  PicturePosition: "0 - fmPicturePositionLeftTop",
  SpecialEffect: "",
  TabIndex: 1,
  TabStop: false,
  Tag: "",
  TextAlign: "",
  Top: "124px",
  TripleState: "",
  Value: "",
  Visible: true,
  Width: "137px",
  WordWrap: "break-word",
};
