export const CommandButton1 = {
  Name: "CommandButton1",
  Accelerator: "",
  AutoSize: false,
  BackColor: "white",
  BackStyle: "solid",
  Cancel:false,
  Caption: "CommandButton1",
  ControlTipText:"",
  Default:false,
  Enabled: true,
  Font: "Arial, Helvetica, sans-serif",
  ForeColor: "black",
  Height: "40px",
  HelpContextId: 0,
  Left: "100px",
  Locked: false,
  MouseIcon: "(None)",
  MousePointer:"",
  Picture: "(None)",
  PicturePosition: "0 - fmPicturePositionLeftTop",
  TabIndex: 1,
  TabStop: false,
  Tag: "",
  TakeFocusOnClick: true,
  Top: "20px",
  Visible: true,
  Width: "132px",
  WordWrap: "break-word",
  
};
