export const CommandButton2 = {
  Name: "CommandButton2",
  Accelerator: "",
  AutoSize: false,
  BackColor: "white",
  BackStyle: "solid",
  Cancel:false,
  Caption: "CommandButton2",
  ControlTipText:"",
  Default:false,
  Enabled: true,
  Font: "Arial, Helvetica, sans-serif",
  ForeColor: "black",
  Height: "50px",
  HelpContextId: 0,
  Left: "339px",
  Locked: false,
  MouseIcon: "(None)",
  MousePointer:"",
  Picture: "(None)",
  PicturePosition: "0 - fmPicturePositionLeftTop",
  TabIndex: 1,
  TabStop: false,
  Tag: "",
  TakeFocusOnClick: true,
  Top: "100px",
  Visible: true,
  Width: "80px",
  WordWrap: "break-word",
  
};
