export const ListBox = {
  Name: "ListBox1",
  BackColor: "white",
  BorderColor: "#eeeeee",
  BorderStyle: "solid",
  BoundColumn: 1,
  ColumnCount: 1,
  ColumnHeads: false,
  ColumnWidths: "",
  ControlSource: "",
  ControlTipText: "",
  Enabled: true,
  Font: "Arial, Helvetica, sans-serif",
  ForeColor: "black",
  Height: "157px",
  HelpContextId: 0,
  ImeMode: "0 - fmIMEModeNOControl",
  IntegralHeight: true,
  Left: "10px",
  ListStyle: "0 - fmListStylePlain",
  Locked: false,
  MatchEntry: "0 - fmMatchEntryFirstLetter",
  MouseIcon: "(None)",
  MultiSelect: "0 - fm-MousePointerDefault",
  MousePointer:"",
  RowSource: "",
  SpecialEffect: "none",
  TabIndex: 6,
  TabStop: true,
  Tag: "",
  Text: "",
  TextAlign: "left",
  TextColumn: -1,
  Top: "10px",
  TopIndex: -1,
  Value: "",
  Visible: true,
  Width: "162px",

};
