export const TextBox = {
  Name: "TextBox1",
  AutoSize: false,
  AutoTab: false,
  AutoWordSelect: true,
  BackColor: "white",
  BackStyle:"",
  BorderColor: "#eeeeee",
  BorderStyle: "solid",
  ControlSource: "",
  ControlTipText: "",
  DragBehavior: "0 - fmDragBehaviotDisabled",
  Enabled: true,
  EnterFieldBehavior: "0 - fmEnterFiledBehaviorSelectAll",
  EnterKeyBehavior: false,
  Font: "Arial, Helvetica, sans-serif",
  ForeColor: "black",
  Height: "50px",
  HelpContextId: 0,
  HideSelection: true,
  ImeMode: "0 - fmIMEModeNOControl",
  IntegralHeight: true,
  Left: "20px",
  Locked: false,
  MaxLength: 0,
  MouseIcon: "(None)",
  MousePointer:"",
  MultiLine: false,
  PasswordChar: "",
  ScrollBars: "1 - fmScrollBarsHorizontal",
  SelectionMargin: true,
  SpecialEffect: "none",
  TabIndex: 4,
  TabKeyBehaviour: false,
  TabStop: false,
  Tag: "",
  TextAlign: "left",
  Top: "100px",
  Value: "",
  Visible: true,
  Width: "150px",
  WordWrap: "break-word",
};
