export const userFormData2 = {
  Name:"UserForm2",
  BackColor: "white",
  BorderColor: "ghostwhite",
  BorderStyle:"fmSBorderStyleNone",
  Caption:"UserForm2",
  Cycle: "0 - fmCycleAllForms",
  DrawBuffer: 32000,
  Enabled: true,
  Font: "Tahoma",
  ForeColor: "black",
  Height: "300px",
  HelpContextId: 0,
  KeepScrollsBarsVisible: "fmScrollBarsNone",
  Left: "0",
  MouseIcon: "(None)",
  MousePointer: "0 - fmMousePointerDefault",
  Picture: "radial-gradient(circle, rgb(0, 0, 0) 0.5px, rgba(0, 0, 0, 0) 0.2px)",
  PictureAlignment: "0 - fmPictureAlignmentTopLeft",
  PictureSizeMode: " 9px 10px",
  PictureTiling: false,
  RightToLeft: false,
  ScrollBars: "0 - fmScrollBarsNone",
  ScrollHeight: 0,
  ScrollLeft: 0,
  ScrollTop: 0,
  ScrollWidth: 0,
  ShowModal: true,
  SpecialEffect: "none",
  StartUpPosition: "0 - Manual",
  Tag: "",
  Top: "0",
  WhatsThisButton: false,
  WhatsThisHelp: false,
  Width: "600px",
  Zoom: "100%"
}


